### ISSUE TITLE
[Bug] Panorama tab groups freezes everything if you have LastPass on and breaks LastPass.

### ISSUE THREAD

**Issue by Gremious** [projectdelphai/panorama-tab-groups#122] opened 2019-06-10 14:26 UTC
I'm not sure if I'm the only one experiencing this, as LastPass is fairly popular and I seem to only reproduce it with LastPass on (?), so I expected to see this reported already. I've not had problems in any other extension so far, so I assume it is on panorma's end. Here's the key notes:

1. Launched Firefox (67.0.1 (64-bit)) with all addons disabled except for [Panorama Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/) and [LastPass ](https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/).

2. Upon launching Firefox, webpages don't load. Opening a new one and attempting to load, say, google.com, just hangs on loading with a blank tab screen.

3. Attempting to open the panorama addon through the extention button
![image](https://user-images.githubusercontent.com/21365711/59201216-91e24a00-8ba2-11e9-907a-c7650ae5bd9d.png)
does nothing.

4. To bypass this, I bookmarked the panorama window `moz-extension://8a28946f-f876-4fd5-b2e4-84290bc05bbb/view.html` and opened that bookmark it a new tab, which after a short period of time, shows this:

![firefox_2019-06-10_16-58-03](https://user-images.githubusercontent.com/21365711/59200471-f69ca500-8ba0-11e9-9f90-3b21ac1ea129.png)

5. I cannot press F12 in this window or open the console through Firefox Menu > Web Devlopers > Web Console. I _can_ open them in any other tab.

5. Pressing "Stop It" makes all tabs instantly resume their loading correctly, stopping the freeze. It also makes the panorama view window open correctly and function as expected. (Though I basically have to do this _almost_ every time I start-up firefox. (I don't know why sometimes it just works normally while a lot of other times this happens)).

6. However, it breaks LastPass, as from this point on, no passwords are filled as if I have none saved. Attempting to open your password vault through the extension:

![image](https://user-images.githubusercontent.com/21365711/59201536-509e6a00-8ba3-11e9-9a24-32f133b4f259.png)

Opens up a blank window.
![image](https://user-images.githubusercontent.com/21365711/59201562-5f851c80-8ba3-11e9-99e2-a51008565696.png)
---
Addiotnal Info:
I tested it in the following way:
Running with all my addons enabled as normal cause the bug, so I disabled ALL of them except panorma. Upon restart, panorama worked perfectly.
Enabled only LastPass: On restart, panorama exhibited the bug.
Disabled LastPass again: On restart, panorama worked perfectly fine.
Enabled LastPass again: On restart, panorama exhibited the bug. 

I am on Windows 10 Enterprise LTSC x64 with 32 GB of memory.

**Comment by Gremious** [comment] 2019-06-10 15:23
(On a sidenote, I switched to bitwarden and so far there are no issues, so I'm happy with that as a personal solution)

**Comment by projectdelphai** [comment] 2019-06-10 15:46
Huh interesting I'm on Windows Enterprise with 32gb on my work computer too with lastpass/ptg and I don't experience the same issues. The blank page on restart is a common bug that vaxul has helped debug and I believe the latest commit should fix. Hopefully the next release which I'm hoping to push in 2 weeks should fix it

**Comment by Gremious** [comment] 2019-06-12 14:22
Great, glad to hear it =)

**Comment by BatmanAoD** [comment] 2019-08-22 23:09
I'm on Mac OS X and cannot reproduce this.

**Comment by projectdelphai** [comment] 2019-09-09 03:32
Closing as not reproduced

**Closed by projectdelphai** 2019-09-09 03:32 UTC
