### ISSUE TITLE
Unable to make a backup of tab groups

### ISSUE THREAD

**Issue by simontom** [projectdelphai/panorama-tab-groups#86] opened 2019-02-16 09:24 UTC
Hi,
I'm on the last version of Panorama Tab Groups with the latest version of FF.
I cannot make a backup of tab groups. I can click on the "Save backup" button but nothing happens.

**Comment by projectdelphai** [comment] 2019-02-17 00:16
duplicate of #73

**Closed by projectdelphai** 2019-02-17 00:16 UTC
