### ISSUE TITLE
Neither Button not Key Command Works; No Way To Access Functionality

### ISSUE THREAD

**Issue by SainteCelery** [projectdelphai/panorama-tab-groups#138] opened 2019-07-31 17:38 UTC
Hey. I've been stubbornly hanging onto the old v.1.0 of Tab Groups and decided to give your Panorama Tab Groups a try. But I can't give it a try. Because there seems to be no way to actually access the add-on. I've tried moving the button all around the toolbars and into the menu and I've tried changing the key command. But no banana. Any suggestions?

**Comment by AzureRaptor** [comment] 2019-08-05 18:58
I am experiencing these symptoms as well.  Toolbar button and shortcut key do absolutely nothing.  😒

**Comment by vaxul** [comment] 2019-08-05 19:04
Would you both please provide detailed information about your environment. 

* which OS + version 
* which Firefox version 
* any other addons which might interfere with PTG

This is something hard to debug. 

I myself use PTG every day without a similar problem. On Windows 10 1903, latest Firefox Developer Edition and current PTG version.

**Comment by AzureRaptor** [comment] 2019-08-05 19:38
Sorry, you're absolutely right.  Sloppy bug report on my part; I've _done_ QC; I oughta know better.

Just tested it two places:  Windows 10 & Ubuntu 16.04.(4?)
Both are running Waterfox 56.2.12 64-bit
I can't think of any addon I'm running that might mess with Panorama.  I really don't run that many.

**Comment by vaxul** [comment] 2019-08-05 20:11
Thank you.

I don't know any details about waterfox, but v56 sounds not as state of art. Firefox is near the 70s. We use some of the latest JavaScript techniques since a while. I've expect that this Waterfox version doesn't cover this.
A higher compatibility might be possible with some tooling, but I'm not sure if it's fits the current development cycle.

**Comment by AzureRaptor** [comment] 2019-08-05 20:35
Thank you very much for your reply.

Well, just bear in mind that Waterfox release numbers don't track FF's, so one can't quite compare those two as a metric.  No other extensions, or websites, fail to function for me, so I think javascript is working fine.

I'll give that Waterfox alpha a go at some point, but I need to research how to make sure it doesn't jack up my _current_ Waterfox profile or extensions first.  I've heard horror stories, and I'm dependent on the few that I run for my sanity and workflow.

**Comment by vaxul** [comment] 2019-08-05 20:38
> Well, just bear in mind that Waterfox release numbers don't track FF's, so one can't quite compare those two as a metric. 

Thanks for the details. Are the developer tools (F12) are available. If, do they show up some meaningful error messages in the console log?

**Comment by AzureRaptor** [comment] 2019-08-05 20:41
Aha!  Thank you for reminding me about that...  Today is yet another sleep-deprived day for me.

All right, I'm in the console tab after F12, but I don't see any output from either hitting ctrl-alt-f or the toolbar button.

**Comment by vaxul** [comment] 2019-08-05 20:50
🤔 that's odd. 

You might report a compatibility issue to the waterfox developers too? 

Maybe some specific techniques aren't supported for now.

I'm not sure if they completely right, but it seems my first thoughts held up to some degree:
https://www.ghacks.net/2019/05/09/waterfox-68-alpha-is-out/

**Comment by SainteCelery** [comment] 2019-08-06 01:57
Hi, sorry for the late response. I am also using Waterfox, so I think we can nail the communication between PTG and Waterfox as the likely source of the issue. I'm on macOS Mojave. I'll give the Waterfox Alpha a try with a dummy profile & see if that solves the problem. Hope so. Will report back later tonight or tomorrow.

**Comment by SainteCelery** [comment] 2019-08-06 02:06
Well, that was easy. Yeah, so, PTG appears to be working exactly as you intended it to in the Waterfox Alpha. I'm not sure if there are other reasons to avoid the Alpha, for now, but I think I may just edge over to it until the changes hit the normal release.

**Comment by vaxul** [comment] 2019-08-20 05:36
@SainteCelery 
Would you please close this issue, if it's resolved?

**Comment by AzureRaptor** [comment] 2019-08-25 22:56
I apologize; I've had to rebuild my rig recently.  I'll try to run this against Waterfox Alpha in a day or two and see what I see; I'll also talk try to the Waterfox project leader and see if he can port over any of the techniques/apis that you're using to 56.  Would you be open to discussing what you're calling, etc. if he were to ask?

**Comment by vaxul** [comment] 2019-08-28 09:22
> if he can port over any of the techniques/apis that you're using to 56

We use JavaScript with WebExtension API. Waterfox v56 is most likely not working caused by JavaScript incompatibility. The JavaScript Engine is tightly coupled to the Browser Version, so I don't think it's possible to selective port something.

**Comment by projectdelphai** [comment] 2019-09-09 03:44
Closing as Waterfox isn't officially supported, incompatible APIs is probably the reason, and resolved by caller

**Closed by projectdelphai** 2019-09-09 03:44 UTC
