### ISSUE TITLE
Unable to restore backup properly

### ISSUE THREAD

**Issue by montypython77** [projectdelphai/panorama-tab-groups#120] opened 2019-06-06 13:00 UTC
I somehow lost all tab groups and tabs in the middle of work. Firefox didn't even crashed, all tabs somehow disappeared and Tab groups were empty. I had  around 600 tabs in seven tab groups.
But I had a backup form one month and a half ago.
After trying to restore, I got all tabs in one unnamed group. All other groups were not loaded correctly. 
I checked backup file. Legit JSON, first all groups, then tabs with group indexes.
Did anyone checked backup and restore functionality at all with more than few tabs?
I only had Panorama Tab Groups installed, I previously used Panorama View, but it was replaced half a year ago. Backup was made by Panorama Tab Groups.
I also tried to restore without Tree Style Tab, which I also use, but with the same result.

**Comment by montypython77** [comment] 2019-06-06 13:03
It looks it's the same issue as #104.

**Comment by projectdelphai** [comment] 2019-06-12 06:59
Closed as duplicate of #94 going to pull all debugging/testing notes in that issue.

**Closed by projectdelphai** 2019-06-12 06:59 UTC
