### ISSUE TITLE
Option to disable the number of tab groups.

### ISSUE THREAD

**Issue by YoussefV** [projectdelphai/panorama-tab-groups#178] opened 2019-11-04 22:45 UTC
You have to give us an option to hide that number of tab groups in the icon. The red box looks like a notification and it is incredibly annoying.

I know how many tab groups I have open, I made them! I don't need to see that 24/7 on my browser

**Comment by NatoBoram** [comment] 2019-11-05 00:30
Oh, that's what it is. I got confused as hell, seeing a red **0 notifications** from the extension's icon. It's not the first time the developer [confused well-known semantics egoistically](https://github.com/projectdelphai/panorama-tab-groups/issues/116).

**Comment by bakkerthehacker** [comment] 2019-11-05 05:03
Duplicate of #170

**Closed** 2019-11-05 05:25 UTC

**Comment by projectdelphai** [comment] 2019-11-05 14:27
Nor is it the first time that you've complained vocally about a project that is developed in people's spare time unpaid. While I like to try and hold this project to good standards, the truth of the matter is that I'm not paid for this nor am I an expert at "well-known semantics" in mozilla add-on development. The current functionality doesn't bother me personally and so when someone like @crass puts in good work to develop a feature like this without me asking, I'm not going to turn him/her away for no reason.

Maybe it's cause I woke up on the wrong side of the bed, but it does hurt to see you call me (or @vaxul or @crass since their ideas/code are the features you're complaining about) egoistical when we're just trying to work on a project that find fun/interesting/worth-while. Especially considering that they're doing this for free and (at least for me) outside of my professional field. 

Going to end this here since I don't want to get hung up about it, but I would appreciate @NatoBoram (and to a lesser degree @YoussefV) if you refrain from demands and have some patience. I'm willing to work with people/merge pull requests/make progress, it will take some time is all.

**Comment by projectdelphai** [comment] 2019-11-05 14:28
Also thanks @bakkerthehacker, not sure where else to post this but you're doing a great job and finding the duplicates and closing them for me. It's really nice to come home from work and not have to crawl through as many issues since you've done some triaging for me already :)

**Comment by YoussefV** [comment] 2019-11-05 15:49
You're 100% right. I didn't mean it to come off as demanding, but I realize it definitely did. Sorry for that, and thanks for the amazing extension

**Comment by projectdelphai** [comment] 2019-11-05 16:25
Don't worry :) I didn't even think of it as demanding myself either. Just waking up early to do some work on PTG before work and seeing me as egoistical for something I didn't even think twice about was a little startling. I don't mind it here and there, but that was the second time BatoBoram has "called me out" for something that I wasn't expecting to get backlash for lol. 

Just makes me worried for the future when actual possible bugs come in that are more serious and I don't want to set the precedence of developers getting the flake for honest mistakes :) At least not in this community if I can help it.

**Comment by YoussefV** [comment] 2019-11-05 16:57
Bugs will happen, people will complain with or without them. Such is the internet.
