### ISSUE TITLE
Unable to Restore from backup

### ISSUE THREAD

**Issue by TriumphRider99** [projectdelphai/panorama-tab-groups#104] opened 2019-04-02 04:03 UTC
I saved a backup twice,  having lost panorama tab groups before. Trying to restore, however, does nothing. Without being able to restore tab groups, this addon is worse than useless.

**Comment by vaxul** [comment] 2019-06-05 20:58
I tested the backup restore mechanism today. It's currently broken. 

Setup:
- Started with 3 tab groups including abouth 10 tabs.
- Backup within the options
- Restore from the fresh backup within the options, without closing any existing tab group or tab

What happens:
- It opens a new window
- opens all the tabs
- hide all tabs
- open /view.html
- shows only a single tab group with all tabs
- if I close the window, Firefox ask to really close all tabs (incl. hidden) within this window

What should happen:
- open a new window
- opens all the tabs
- hide all tabs
- open /view.html
- show all tab groups with each tabs

The odd thing is, that the `groupId` seem to be lost, even if it's written.

**Comment by projectdelphai** [comment] 2019-06-12 06:58
Closed as duplicate of #94 going to pull all debugging/testing notes in that issue.

**Closed by projectdelphai** 2019-06-12 06:58 UTC
